# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for FiveAtlas. Builds on Windows and macOS from one file.

One-FOLDER build on purpose, not --onefile: onefile re-extracts a few hundred MB
to %TEMP% on every launch (15-30 s startup, and the antivirus rescans it each
time). The folder build starts in a couple of seconds and zips just as well.
On macOS the same folder is wrapped in a .app bundle, which is the only shape
Finder, Gatekeeper and codesigning all understand.

Build with:  pyinstaller --noconfirm FiveAtlas.spec
(run `npm run build` in frontend/ first -- the built UI is bundled in)

macOS note: PyInstaller cannot cross-compile, and it cannot make a universal2
build unless every wheel is universal2 (imagecodecs is not). Build on the arch
you are shipping to -- an arm64 Mac produces an Apple Silicon app, an Intel Mac
or a macos-13 CI runner produces an Intel one.
"""
import os
import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_dynamic_libs, collect_submodules

APP_DIR = Path(SPECPATH).resolve()
BACKEND = APP_DIR / "backend"
DIST_UI = APP_DIR / "frontend" / "dist"

MACOS = sys.platform == "darwin"

# The build scripts pass the version in, so the number baked into the .app is
# always the one on the filename and the git tag. It used to be a literal here,
# which drifted: the spec said 0.1.0 while backend/config.py said 0.4.1, so a
# download could be labelled with one version while stamping a different one
# into the provenance of every region file it edited.
VERSION = os.environ.get("FIVEATLAS_VERSION", "0.0.0-dev")

# Bake the version into a module the frozen app can import.
#
# config.py used to read FIVEATLAS_VERSION from the environment, but that is a
# BUILD-time variable: inside the frozen app it is unset, so the running app fell
# back to a hardcoded literal and stamped THAT into the provenance of every region
# file it edited. A build called 0.4.5 recorded 0.4.1, which defeats the entire
# point of recording a version. Writing it to a module instead means the number in
# the filename, the number in Info.plist and the number in the provenance trail
# are the same number by construction.
(BACKEND / "_buildinfo.py").write_text(
    '"""Generated by FiveAtlas.spec at build time. Do not edit, do not commit."""\n'
    f'VERSION = "{VERSION}"\n',
    encoding="utf-8",
)

if not (DIST_UI / "index.html").exists():
    raise SystemExit(
        f"frontend not built: {DIST_UI / 'index.html'} is missing.\n"
        "Run `npm run build` in atlas_editor/frontend first."
    )

# The backend imports its modules by bare name (import datasets, import scan...),
# so they have to be collected explicitly rather than discovered from launcher.py.
#
# Discovered from the directory rather than hand-listed. A hand-written list is a
# trap: add a module to backend/, import it from app.py, and everything works
# from source while the FROZEN build dies with ModuleNotFoundError -- a failure
# that only appears in the packaged app, which is the worst place to find it.
# (Nearly hit exactly this: backend/provenance.py was added and imported by
# app.py while the list here still had eleven names.)
_SKIP = ("smoke_test", "stain_probe")          # dev scripts, not part of the app
BACKEND_MODULES = sorted(
    p.stem for p in BACKEND.glob("*.py")
    if not p.stem.startswith(("verify_", "diag_", "debug_", "test_"))
    and not p.stem.endswith("_smoke")
    and p.stem not in _SKIP
)
if "app" not in BACKEND_MODULES:
    raise SystemExit(f"backend/app.py not found under {BACKEND}")

# uvicorn resolves its loop/protocol implementations at runtime by string.
UVICORN_HIDDEN = collect_submodules("uvicorn")

hiddenimports = (
    BACKEND_MODULES
    + UVICORN_HIDDEN
    + collect_submodules("imagecodecs")     # JPEG2000 decode for the morphology pyramid
    + [
        "anyio", "click", "h11",
        "shapely", "shapely.geometry", "shapely.ops", "shapely.strtree",
        "shapely.validation", "shapely._geos",
        "tifffile", "zarr", "numcodecs",
        "PIL.Image", "PIL.ImageDraw",
        # ruamel.yaml is a namespace package and its C backend is loaded by
        # name, so neither is found by following imports alone.
        "ruamel.yaml", "ruamel.yaml.clib", "ruamel.yaml.main",
    ]
)

# The tkinter picker is only a fallback, and on macOS it is never reached (see
# nativedialog._pick_mac). Homebrew/pyenv Pythons often ship without Tk, so ask
# for it only when it actually imports -- otherwise the build fails on a module
# the app does not need.
try:
    import tkinter  # noqa: F401
    hiddenimports += ["tkinter", "tkinter.filedialog"]
except Exception:
    pass

# shapely ships GEOS as bundled DLLs/dylibs; imagecodecs ships a pile of codecs.
binaries = collect_dynamic_libs("shapely") + collect_dynamic_libs("imagecodecs")

a = Analysis(
    [str(APP_DIR / "launcher.py")],
    pathex=[str(BACKEND), str(APP_DIR)],
    binaries=binaries,
    datas=[(str(DIST_UI), "frontend_dist")],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["matplotlib", "scipy", "pandas", "IPython", "notebook", "pytest"],
    # Our backend/datasets.py shares its name with the HuggingFace `datasets`
    # package, and pyinstaller-hooks-contrib's hook for THAT package tells
    # PyInstaller to ship the module as plain source beside the bytecode. It
    # was harmless (no secrets in it) but it is the only .py in the bundle and
    # a standing invitation to wonder why. Bytecode only, like everything else.
    module_collection_mode={"datasets": "pyz"},
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="FiveAtlas",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    # Windows: console stays ON, so colleagues get the URL, the workdir path and
    # any error text in the window instead of a silent failure.
    # macOS: a .app has no console, so it goes off and launcher.py mirrors the
    # same text to FiveAtlas.log plus a native alert on a fatal error.
    console=not MACOS,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,          # host arch; see the module docstring
    codesign_identity=None,    # PyInstaller ad-hoc signs on arm64, which is enough to run
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="FiveAtlas",
)

if MACOS:
    app = BUNDLE(
        coll,
        name="FiveAtlas.app",
        icon=None,
        bundle_identifier="com.fivelab.fiveatlas",
        version=VERSION,
        info_plist={
            "CFBundleName": "FiveAtlas",
            "CFBundleDisplayName": "FiveAtlas",
            "CFBundleShortVersionString": VERSION,
            "CFBundleVersion": VERSION,
            "NSHighResolutionCapable": True,
            # 11.0 is only honest if every binary inside agrees -- CI runs
            # tests/check_min_os.py against the built bundle to make sure.
            "LSMinimumSystemVersion": "11.0",
            # An agent app: no Dock icon, no Dock menu. The process has no
            # Cocoa event loop (it is a uvicorn server that opens your browser),
            # so with a Dock icon it would bounce, then read "Not Responding",
            # and the Dock's Quit could not stop it. The UI is the handle: the
            # sidebar's Quit button, and a heartbeat watchdog for a closed tab.
            "LSUIElement": True,
            "NSHumanReadableCopyright": "Five Lab",
        },
    )
